### ISSUE TITLE
Feature Request: Direct send to OBS Text GDI+ Source through websocket

### ISSUE THREAD

**Issue by DachsbauTV** [aw-was-here/Now-Playing-Serato#103]
Hey hey,

First off: Great work improving this app!

I was struggling to get the remote option to work, that's why in our last show I detoured to a local txt file which would be synced through our cloud to the OBS PC.
It actually worked quite well, however, I figured it would be a great addition to actually send the text straight to OBS.

This should actually be quite easy through the websockets plugin, which is widely used by companion anyways.
This would be the corresponding API https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#gettextgdiplusproperties

This would allow to send the track info straight over the network to OBS with minimal delay.

**Comment by aw-was-here** [comment]
OBS WebSocket Plugin support was committed as #100.  Was there something more that is needed?

**Comment by DachsbauTV** [comment]
Ah amazing timing haha
Was looking at the 2.0.0 release and didn't see it.

OBS websocket allows GDI+ control for quite a while now so I guess your implementation should do the trick :) I am happy to try it next week

**Comment by aw-was-here** [comment]
Hopefully by then I have things more stabilized haha :+1:

**Comment by aw-was-here** [comment]
I'm going to go ahead and close this one since I'm sitting here staring at my OBS screen getting updated via the GDI+ websocket support. I'll likely be cutting a test release soon so will appreciate any bugs/weirdness/etc that you find.

Thanks!

**Comment by DachsbauTV** [comment]
Hey Allen,

Really excited to give this a test drive! "unfortunately" i am on holiday now for two weeks, but I'll test it thoroughly as soon as I am back.

cheers,
Fred
