### ISSUE TITLE
add support for MPRIS

### ISSUE THREAD

**Issue by aw-was-here** [aw-was-here/Now-Playing-Serato#12]
should be able to support more than just Serato now, so let's keep it easy and try to add Mixxx.

**Comment by aw-was-here** [comment]
See also https://github.com/mixxxdj/mixxx/pull/3483

**Comment by aw-was-here** [comment]
As for an insane stop gap, ways to get the current metadata:
- pretend to be icecast
- read the window title
- act as a midi controller?

Once the artist/title info has been grabbed, try to find it in the sqlite db to pull out the other metadata.

:shrug:

**Comment by Be-ing** [comment]
If you're interested in moving this forward with Mixxx, I encourage you to help with https://github.com/mixxxdj/mixxx/pull/3483 rather than work on really hacky workarounds.

**Comment by aw-was-here** [comment]
Yup, totally agree @Be-ing ! My read of the Mixxx PR was that the major blocker appeared to be some arguing over MPRIS which I don't really have an opinion on.  In the mean time, I did rebase it onto mixxx main and was able to build a trivial reader for this project. :dancers:

**Comment by aw-was-here** [comment]
Played around a bit.  Using MPRIS is a much better option with the current functionality in that PR.  Plus it opens the door for VLC, etc.

**Comment by aw-was-here** [comment]
Looks like latest changes in mixxx pr dropped xesam:url? :frowning:

**Comment by aw-was-here** [comment]
https://github.com/aw-was-here/mixxx/tree/mpris2

**Comment by aw-was-here** [comment]
ok, my build of mixxx + the mpris2 branch of now playing + custom hacking on the now playing preferences works.  Lots of bugs hit (not surprising as now playing's main isn't very stable at the moment) and definitely a few other things that need to get fixed, but it is definitely progress.
