### ISSUE TITLE
No Cover art with Aif and flac

### ISSUE THREAD

**Issue by TIMOUNGEGE** [aw-was-here/Now-Playing-Serato#123]
Hi
It works with mp3 but not with others lossless formats

Regards

**Comment by aw-was-here** [comment]
Thanks for the bug report.

Just a note that I've confirmed this issue with flac.  I haven't tried aif yet given my first attempt with flac failed. Most of my collection is in m4a+alac and mp3 and those seem to be ok.  Almost certainly a bug with the tag library I'm using.  I've been debating switching to something else so this bug might just do it...

**Comment by aw-was-here** [comment]
AIFF definitely going to be broken: https://github.com/devsnd/tinytag/issues/103

**Comment by aw-was-here** [comment]
and next release of TinyTag will support FLAC image loading 😄 

https://github.com/devsnd/tinytag/issues/82

**Comment by aw-was-here** [comment]
FYI: I've submitted a code change for tinytag to understand AIFF.  It has yet to be accepted, but hopefully it is some progress forward.

**Comment by aw-was-here** [comment]
Released 2.0.1 that includes the fixes required for this issue.  Many thanks for the bug report @TIMOUNGEGE !
