### ISSUE TITLE
OBS WebSocket issues

### ISSUE THREAD

**Issue by aw-was-here** [aw-was-here/Now-Playing-Serato#128]
1. It is _very_ noisy in debug.
2. It does not shutdown when asked.

**Comment by DachsbauTV** [comment]
Just fyi: obs websocket apparently has a deeper issue somewhere, as there are currently quite a few OBS and companion related problems with it: https://github.com/bitfocus/companion-module-obs-studio/issues/52

**Comment by aw-was-here** [comment]
Hmm.  Actually, I'm pretty sure in this case the bug was on my side. haha.  I think I've got it fixed now though.

Thanks for the heads up! I'll keep an 👁️ out.

**Comment by aw-was-here** [comment]
OK, both of these bugs appear to be fixed.
